server:
  port: 30001
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  application:
    name: I01-agentscope-agentstate

agentscope:
  model:
    provider: dashscope
  dashscope:
    api-key: ${DASHSCOPE_API_KEY}
    model-name: qwen-plus
    stream: true
