server:
  port: 10040

  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  application:
    name: memory

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 12