server:
  port: 10005

spring:
  application:
    name: SA05-springai-alibaba-agent-skill

  # Spring AI DashScope 配置
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        model: qwen-plus
        temperature: 0.7

# ReactAgent 配置
agent:
  react:
    name: skills-agent
    enable-logging: true
    classpath-path: skills

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
