<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.happyhai.springai.alibaba</groupId>
        <artifactId>springai-alibaba-admin</artifactId>
        <version>1.0.0</version>
    </parent>
    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-dashscope</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-agent-framework</artifactId>
        </dependency>
    </dependencies>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>springai-alibaba-agent</artifactId>

    <description>
        RAG
    </description>

   <modules>
       <module>springai-alibaba-agent-base</module>
       <module>springai-alibaba-agent-memory</module>
       <module>springai-alibaba-agent-tool</module>
       <module>springai-alibaba-agent-skill</module>
       <module>springai-alibaba-agent-loop</module>
       <module>springai-alibaba-agent-comprehensive</module>
           <module>springai-alibaba-agent-mcp</module>
    </modules>

    <packaging>pom</packaging>


</project>
