<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.happyhai.springai.alibaba</groupId>
        <artifactId>springai-alibaba-admin</artifactId>
        <version>1.0.0</version>
    </parent>
    <dependencies>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-client-chat</artifactId>
        </dependency>


    </dependencies>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>springai-alibaba-model</artifactId>

    <description>
        Model
    </description>

    <modules>
        <module>springai-alibaba-model-openai</module>
        <module>springai-alibaba-model-dashscope</module>
    </modules>
    <packaging>pom</packaging>

</project>
