server:
  port: 10021
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true



spring:
  application:
    name: springai-alibaba-agent-comprehensive
  ai:
    mcp:
      client:
        type: SYNC
        toolcallback:
          enabled: true
        sse:
          connections:
            zetlight-mcp-server:
              url: ${MCP_SERVER_URL:http://localhost:8080}
  data:
    redis:
      host: localhost
      port: 6379
      password: "123456"
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

agent:
  react:
    name: aquarium_mcp_agent
    enable: true
    classpath-path: skills

logging:
  level:
    org.happyhai.springai.alibaba.comprehensive: DEBUG
    com.alibaba.cloud.ai: DEBUG
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
